#!/bin/zsh

[ $# = 0 ] && set -- -e $'   #hel \tlo\n  #  hi\n
#; O + 1 2 O 3
D ; 3 O + 19 TRUE

# ; O ! 123 O ~ "   12 34"\n__END__
#; O ! 123 O ~ "   12 34"
#; O 1 O !2
#3 O ~"  12"
#O 12
#O "1''\\'$'"
';
printf "%s\n__END__" "$2" | sed -nEf ./knight.sed
