#!/bin/zsh

[ $# = 0 ] && set -- -e $'   #hel \tlo\n  #  hi\n
#; O + 1 2 O 3
# ; OUTPUT (; & 0 1 "A") OUTPUT 3
D "123\n\t"
; O 3 O + 19 TRUE


# + 1 O & + 1 2 O F
# O ; 3 O + 19 TRUE

# ; O ! 123 O ~ "   12 34"\n__END__
#; O ! 123 O ~ "   12 34"
#; O 1 O !2
#3 O ~"  12"
#O 12
#O "1''\\'$'"
';
printf "%s\nX__END__" "$2" | sed -nEf ./knight.sed
