#!/bin/zsh

[ $# = 0 ] && set -- -e $'   #hel \tlo\n  #  hi\n
#; O + 1 2 O 3
# ; OUTPUT (; & 0 1 "A") OUTPUT 3
; = a 3
D a
; O 3 O + 19 TRUE


# + 1 O & + 1 2 O F
# O ; 3 O + 19 TRUE

# ; O ! 123 O ~ "   12 34"\n__END__
#; O ! 123 O ~ "   12 34"
#; O 1 O !2
#3 O ~"  12"
#O 12
#O "1''\\'$'"
';
printf "%s\nX__END__" "$2" | sed -nEf =(cat ./knight.sed | sed \
	-e $'s/`VARS`/\x12/g' \
	-e $'s/`NL`/\x13/g' \
	-e $'s/`PS`/\x14/g' \
	)
